x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    output:
      a:
        path: /veld/output/a/data.json
        format: "json"
        kind: "dummy data"
      b:
        path: /veld/output/b/log.txt
        format: "txt"
        kind: "dummy data"

services:
  veld:
    build: .
    volumes:
      - ./fetch.sh:/veld/executable/fetch.sh
    command: sh /veld/executable/fetch.sh

