x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    input:
      type: "environment variable"
      id: "id"
    output:
      type: "files"
      format: "json"
      path: /veld/output/data.json
      content: "dummy data"

services:
  veld:
    build: .
    volumes:
      - ./fetch.sh:/veld/executable/fetch.sh
    command: sh /veld/executable/fetch.sh

